### ISSUE TITLE
write utility method for below functionality

### ISSUE THREAD

**Issue by nehagandhi20** [moglideveloper/CollegeStyleStudy#2]
_From @moglideveloper on April 14, 2015 8:6_

@Override
	public boolean equals(Object obj) {
		Optional<Object> optional = Optional.fromNullable(obj);
		
		
		if(optional.isPresent() && optional.get().getClass().isAssignableFrom(this.getClass())){
			//here is business logic
		}else{
			return false ;
		}
		
	}

_Copied from original issue: nehagandhi20/LearnGuava#15_

**Comment by moglideveloper** [comment]
This implementation is now available in basic.utils.Utils.java
